<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RepositoryUrl>https://github.com/hansen-consultancy/Dev</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageId>HC.$(AssemblyName)</PackageId>
    <PackAsTool>True</PackAsTool>
    <ToolCommandName>dev</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <Version>1.12.0</Version>
    <Description>A development tool to simplify common tasks in .NET projects</Description>
    <Authors>Hansen Consultancy</Authors>
    <PackageIcon>logo-128x128.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>https://github.com/hansen-consultancy/Dev/blob/main/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="nupkg\**" />
    <EmbeddedResource Remove="nupkg\**" />
    <None Remove="nupkg\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SolutionPersistence" Version="1.0.52" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
    <PackageReference Include="ThisAssembly.AssemblyInfo" Version="1.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ThisAssembly.Git" Version="1.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="logo-128x128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="CHANGELOG.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
